### ISSUE TITLE
@glimmer/syntax 0.92.1 release issues

### ISSUE THREAD

**Issue by davidtaylorhq** [glimmerjs/glimmer-vm#1621]
We're seeing lots of failures when updating from `@glimmer/syntax` 0.92.0 to 0.92.1:

e.g. with eslint:
```
Error: Failed to load parser 'ember-eslint-parser' declared in '.eslintrc.cjs#overrides[0]': Cannot find module '/__w/discourse/discourse/node_modules/.pnpm/ember-eslint-parser@0.4.3_@babel+core@7.25.2_eslint@[8](https://github.com/discourse/discourse/actions/runs/10837079714/job/30072252018?pr=28885#step:11:9).57.0/node_modules/@glimmer/syntax/dist/dev/index.cjs'
...
```
Embroider build:

```
[BABEL] /__w/discourse/discourse/app/assets/javascripts/discourse/node_modules/.embroider/rewritten-app/assets/discourse.js/discourse.js: Cannot find module '/__w/discourse/discourse/app/assets/javascripts/discourse-widget-hbs/node_modules/@glimmer/syntax/dist/dev/index.cjs' (While processing: "/__w/discourse/discourse/node_modules/.pnpm/@embroider+core@3.4.15_@glint+template@1.4.1-unstable.ff9ea6c/node_modules/@embroider/core/src/portable-babel-launcher.js")
```

and more. PR here: https://github.com/discourse/discourse/pull/28885

Looking at the [npm code browser](https://www.npmjs.com/package/@glimmer/syntax/v/0.92.1?activeTab=code), it seems like the `dist/` directory is missing from the released package?

**Comment by davidtaylorhq** [comment]
I guess this is fixed by https://github.com/glimmerjs/glimmer-vm/commit/1d935c93dc1f1a6965f43791b2700c33c4aeb0f4, but we need to trigger a release of `@glimmer/syntax` somehow 🤔

**Comment by NullVoxPopuli** [comment]
yea, I need to sync with @real_ate on some release-plan stuff (or get some focus time to debug).

I need to trigger a re-release of all the packages, because I forgot to add the build step when switching over to release-plan.

You make a good point that since `@glimmer/syntax` is used outside our ecosystem (in astexplorer, prettier, etc) -- I should get this fixed as asap-ily as possible

**Comment by NullVoxPopuli** [comment]
0.92.3 is out
![image](https://github.com/user-attachments/assets/7507e681-3cee-4167-a5f1-dfe4b5ccc468)

aaaand, the ember upgrade PR is green: https://github.com/emberjs/ember.js/pull/20746
